version: "3.7"


services:
    app:
        container_name: app
        image: app
        ports:
        - "80:8000"
        build:
            context: .
            dockerfile: Dockerfile

    database:
        image: postgres
        container_name: "localhost"
#        command: postgres -p 8080
        ports:
          - "5432:5432"
